#dev version, loacl testing
import gradio as gr

def process_video(video):
    # placeholder for now
    return video, "AI Probability: 0.00 (dummy)"

with gr.Blocks(theme=gr.themes.Soft()) as demo:

    gr.Markdown(
        """
        # 🎥 AI Video Detection System
        Upload a video and detect whether it was generated by AI.
        """
    )

    with gr.Row():
        with gr.Column(scale=1):
            video_input = gr.Video(
                label="📤 Upload Video",
                height=300
            )

            analyze_btn = gr.Button(
                "Analyze Video",
                variant="primary"
            )

            gr.Markdown(
                """
                ### How it works
                - Upload a video file
                - Model analyzes frames
                - Returns AI probability + heatmap visualization
                """
            )

        with gr.Column(scale=1):
            video_output = gr.Video(
                label="🧠 Analysis Output",
                height=300
            )

            result = gr.Textbox(
                label="Confidence Score",
                interactive=False
            )

    analyze_btn.click(
        fn=process_video,
        inputs=video_input,
        outputs=[video_output, result]
    )

demo.launch()