import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from pathlib import Path
import random

# Import the Audio Architecture
from model_architecture import AudioExpert

class AudioOnlyDataset(Dataset):
    def __init__(self, root_dirs):
        self.files = []
        for d in root_dirs:
            # We look for the .pt files generated by process_data.py
            self.files.extend(list(Path(d).rglob("*.pt")))
        
        random.shuffle(self.files)
        print(f">> Found {len(self.files)} samples for Audio training.")
        
    def __len__(self): return len(self.files)

    def __getitem__(self, idx):
        # Load the combined data file
        try:
            data = torch.load(self.files[idx], weights_only=False)
            
            # The file contains: (1, 1, 128, 128). 
            # We need (1, 128, 128) so the DataLoader stacks it into (Batch, 1, 128, 128)
            spec = data['audio'].squeeze(0) 
            
            label = torch.tensor([data['label']], dtype=torch.float32)
            
            # Basic Augmentation: Add random noise to prevent overfitting on silence
            if random.random() > 0.5:
                noise = torch.randn_like(spec) * 0.05
                spec = spec + noise
                
            return spec, label
            
        except Exception as e:
            # Fallback for corrupt files
            print(f"Error loading {self.files[idx]}: {e}")
            return torch.zeros((1, 128, 128)), torch.tensor([0.0])

def train_audio_branch():
    # Setup
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"--- Training Audio Expert on {device} ---")
    
    # 1. Load Data
    train_dirs = ["data/processed_data/real", "data/processed_data/fake"]
    dataset = AudioOnlyDataset(train_dirs)
    
    if len(dataset) == 0:
        print("Error: No data found. Did you run process_data.py?")
        return

    # Batch size can be larger since audio is small
    loader = DataLoader(dataset, batch_size=16, shuffle=True)
    
    # 2. Initialize Model
    model = AudioExpert().to(device)
    optimizer = optim.Adam(model.parameters(), lr=0.001)
    criterion = nn.BCEWithLogitsLoss()
    
    print("Starting Training...")
    
    # 3. Train
    epochs = 25
    for epoch in range(1, epochs+1):
        total_loss = 0
        correct = 0
        total = 0
        
        model.train()
        for specs, labels in loader:
            specs = specs.to(device)   # (B, 1, 128, 128)
            labels = labels.to(device) # (B, 1)
            
            # Skip empty batches (rare edge case)
            if specs.size(0) == 0: continue
            
            optimizer.zero_grad()
            
            # Forward
            outputs = model(specs)
            loss = criterion(outputs, labels)
            
            # Backward
            loss.backward()
            optimizer.step()
            
            total_loss += loss.item()
            
            # Calculate Accuracy
            preds = torch.sigmoid(outputs) > 0.5
            correct += (preds == labels).sum().item()
            total += labels.size(0)
            
        avg_loss = total_loss / len(loader)
        acc = correct / total if total > 0 else 0
        
        print(f"Epoch {epoch} | Loss: {avg_loss:.4f} | Acc: {acc:.2%}")
        
        # Stop early if it's too good (prevents memorizing specific songs/voices)
        if acc > 0.98:
            print(">> Early Stopping: Accuracy is very high.")
            break

    # 4. Save
    torch.save(model.state_dict(), "./models/audio_expert.pth")
    print("\nTraining Complete.")
    print(">> 'audio_expert.pth' saved.")

if __name__ == "__main__":
    train_audio_branch()